name: CI

on:
  pull_request:
    paths:
      - "opencog/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build_opencog_images:
    name: Build opencog images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Build all opencog images
        working-directory: opencog
        run: ./docker-build.sh -bsl
